---
title: "Modeling and prediction for movies"
output: 
  html_document: 
    fig_height: 4
    highlight: pygments
    theme: spacelab
---

## Setup

### Load packages and data

```{r load-packages, message = FALSE}
library(ggplot2)
library(dplyr)
library(statsr)
### Load data
load("movies.Rdata")
```

* * *

## Part 1: Data

The goal of this section is: 
*Describe how the observations in the sample are collected and the implications of this data collection method on the scope of inference (generalizability / causality).*

###Introduction to the Data

The dataset "movies" is comprised of 651 **randomly sampled movies** produced and released before 2016. The movies are from American Studios.  (We know this because the MPAA Ratings in teh data applies only to American movies.)  This dataset includes information from both Rotten Tomatoes and IMDb.

####About Rotten Tomatoes 
(see https://www.rottentomatoes.com/about/):

Rotten Tomatoes and the Tomatometer™ rating is the most trusted measurement of quality entertainment. As the leading online aggregator of movie and TV show **reviews from professional critics**, Rotten Tomatoes offers the most comprehensive guide to what's fresh. The world famous Tomatometer™ rating represents the percentage of positive professional reviews for films and TV shows and is used by millions every day, to help with their entertainment viewing decisions. Rotten Tomatoes designates the best reviewed movies and TV shows as Certified Fresh. That accolade is awarded with Tomatometer ratings of 75% and higher and a required minimum number of reviews. 

####About IMDB 
(see https://en.wikipedia.org/wiki/IMDb)

The Internet Movie Database (abbreviated IMDb) is an online database of information related to films, television programs and video games, including cast, production crew, fictional characters, biographies, plot summaries, trivia and reviews. As of June 2016, IMDb has approximately 3.7 million titles (including episodes) and 7 million personalities in its database.

The site enables registered users to submit new material and request edits to existing entries. Although all data is checked before going live, the **system has been open to abuse and occasional errors are acknowledged**. Users are also invited to rate any film on a scale of 1 to 10, and the totals are converted into a weighted mean-rating that is displayed beside each title, with online filters employed to deter ballot-stuffing. The site also features message boards which stimulate regular debates among authenticated users.

###Scope of Inference
In *Introduction to the Data* above, a few pharases have been **highlighted**.  These phrases provide key information about the generalizability of the data.  This information suggests the dataset should be considered the result of an observational retrospective study that uses a random sampling design to select a representative sample from U.S. movies. When random sampling has been employed in data collection, the results should be generalizable to the target population. Therefore, the results of the analysis should be generailizable to all the movies relased between 1970 - 2014.

Note that observational studies show associations. In a data analysis, association does not imply causation. Causation can only be inferred from a randomized experiment.  This analysis does not meet the requirements of an experiment.  

Sources of Bias

- “Face-to-face interviews” performed at the University of Chicago introduce a “convenience bias” as people close to Chicago may be more likely to participate.
- The study may suffer from “voluntary response bias” since people with strong responses participate. The voluntary participants may not be representative of the US population.

Non-Response Bias:  Simple random sampling means that each case in the population has an equal chance of being included and there is no implied connection between the cases in the sample. However, even when people are picked at random, caution
must be exercised if the non-response is high. If only 30% of the people randomly sampled for a survey respond, then it is unclear whether the results are representative of the entire population. This non-response bias can skew results.

Voluntary Response Bias:  Another common downfall is a convenience sample, where individuals who are easily
accessible are more likely to be included in the sample. For instance, if a political survey
is done by stopping people walking in the Bronx, this will not represent all of New York
City. It is often difficult to discern what sub-population a convenience sample represents.

* * *

## Part 2: Research question

The project objective for this section:

*Develop a research question that you want to answer using these data and a multiple linear regression model. You should phrase your research question in a way that matches up with the scope of inference your dataset allows for.  Include a brief discussion why this question is of interest to you and/or your audience.*


* * *

## Part 3: Exploratory data analysis

The project objective for this section:

*Perform exploratory data analysis (EDA) that addresses the research question. The EDA should contain numerical summaries and visualizations. Each R output and plot should be accompanied by a brief interpretation.*


* * *

## Part 4: Modeling

The project objective for this section:

*Develop a multiple linear regression model to predict a numerical variable in the dataset. The response variable and the explanatory variables can be existing variables in the dataset, or new variables you create based on existing variables.*

* * *

## Part 5: Prediction

The project objective for this section:

*Pick a movie from 2016 (a new movie that is not in the sample) and do a prediction for this movie using your the model you developed and the `predict` function in R. Also quantify the uncertainty around this prediction using an appropriate interval.*


* * *

## Part 6: Conclusion

The project objective for this section:

*A brief summary of your findings from the previous sections without repeating your statements from earlier as well as a discussion of what you have learned about the data and your research question. You should also discuss any shortcomings of your current study (either due to data collection or methodology) and include ideas for possible future research.*
